In [1]:
# utilizado para la manipulación de directorios y rutas
import os

# Cálculo científico y vectorial para python
import numpy as np

# Libreria para graficos
from matplotlib import pyplot

# Modulo de optimizacion en scipy
from scipy import optimize

# le dice a matplotlib que incruste gráficos en el cuaderno
%matplotlib inline

In [2]:
#from google.colab import drive
#drive.mount('/content/gdrive')

In [3]:
data = np.loadtxt("wine_preparado.csv", delimiter=',')
# print(data)
X, y = data[:, 1:], data[:, 0]
print(X.shape)
print(y.shape)

(178, 13)
(178,)


In [4]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3.])

In [5]:
# data.shape
X.shape[1]

13

In [6]:
input_layer_size  = 13
num_labels = 3
m = y.size

In [7]:
def calcularSigmoide(z):
    # Calcula la sigmoide de z.

    return 1.0 / (1.0 + np.exp(-z))

In [8]:
def calcularCosto(theta, X, y, lambda_):
    # Inicializa algunos valores utiles
    m = y.size

    # convierte las etiquetas a valores enteros si son boleanos
    if y.dtype == bool:
        y = y.astype(int)

    J = 0
    grad = np.zeros(theta.shape)

    h = calcularSigmoide(X.dot(theta.T))

    temp = theta
    temp[0] = 0

    J = (1 / m) * np.sum(-y.dot(np.log(h)) - (1 - y).dot(np.log(1 - h))) + (lambda_ / (2 * m)) * np.sum(np.square(temp))

    grad = (1 / m) * (h - y).dot(X)
    # Se aplica regularizacion en la siguiente linea
    grad = grad + (lambda_ / m) * temp

    return J, grad

In [9]:
# valores de prueba para los parámetros theta
theta_t = np.array([-2, -1, 1, 2], dtype=float)

# valores de prueba para las entradas
X_t = np.concatenate((np.ones((5, 1)), np.arange(1, 16).reshape(5, 3, order='F')/10.0), axis=1)
print(X_t)
# valores de testeo para las etiquetas
y_t = np.array([1, 0, 1, 0, 1])

# valores de testeo para el parametro de regularizacion
lambda_t = 3

[[1.  0.1 0.6 1.1]
 [1.  0.2 0.7 1.2]
 [1.  0.3 0.8 1.3]
 [1.  0.4 0.9 1.4]
 [1.  0.5 1.  1.5]]


In [10]:
J, grad = calcularCosto(theta_t, X_t, y_t, lambda_t)

print('Costo         : {:.6f}'.format(J))
print('Costo esperadot: 2.534819')
print('-----------------------')
print('Gradientes:')
print(' [{:.6f}, {:.6f}, {:.6f}, {:.6f}]'.format(*grad))
print('Gradientes esperados:')
print(' [0.146561, -0.548558, 0.724722, 1.398003]');

Costo         : 2.534819
Costo esperadot: 2.534819
-----------------------
Gradientes:
 [0.146561, -0.548558, 0.724722, 1.398003]
Gradientes esperados:
 [0.146561, -0.548558, 0.724722, 1.398003]


In [11]:
def oneVsAll(X, y, num_labels, lambda_):

    m, n = X.shape

    all_theta = np.zeros((num_labels, n + 1))

    # Agrega unos a la matriz X
    X = np.concatenate([np.ones((m, 1)), X], axis=1)


    for c in np.arange(num_labels):
        initial_theta = np.zeros(n + 1)
        options = {'maxiter': 50}
        res = optimize.minimize(calcularCosto,
                                initial_theta,
                                (X, (y == (c + 1)), lambda_),
                                jac=True,
                                method='BFGS',
                                options=options)

        all_theta[c] = res.x

    return all_theta

In [17]:
lambda_ = 0.1
all_theta = oneVsAll(X, y, num_labels, lambda_)

C:\Users\FERNANDO\AppData\Local\Temp\ipykernel_7180\3442295675.py:4: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-z))
C:\Users\FERNANDO\AppData\Local\Temp\ipykernel_7180\2753339385.py:17: RuntimeWarning: divide by zero encountered in log
  J = (1 / m) * np.sum(-y.dot(np.log(h)) - (1 - y).dot(np.log(1 - h))) + (lambda_ / (2 * m)) * np.sum(np.square(temp))


In [13]:
print(all_theta)

[[-1.40742663e+00 -1.24591511e+00  1.46004811e+00  3.83602622e+00
  -1.02047469e+00  1.15455706e-02 -5.52822082e-01  3.23842666e+00
   4.67402045e-01 -2.41615157e+00 -3.60775623e-01 -3.92177725e-01
   1.69408592e+00  2.26615313e-02]
 [ 2.43584900e+00  1.42929266e+00 -1.35715925e+00 -3.43455243e+00
   4.95454918e-01 -1.09517123e-02  5.84100535e-01  1.51579377e+00
   2.42303263e+00  1.75710755e+00 -3.04455182e+00  3.72120999e+00
  -1.54448015e+00 -1.89126234e-02]
 [-2.84243751e-01 -4.06629285e-01  1.11744848e+00  4.90906018e-01
   8.63145323e-02  4.61538990e-02 -1.14278181e+00 -4.07174170e+00
  -4.09978244e-01 -1.40392269e+00  1.58025409e+00 -1.30343232e+00
  -2.49568832e+00  3.47413721e-03]]


In [18]:
def predictOneVsAll(all_theta, X):
    m = X.shape[0]
    num_labels = all_theta.shape[0]

    p = np.zeros(m)

    # Add ones to the X data matrix
    X = np.concatenate([np.ones((m, 1)), X], axis=1)
    p = np.argmax(calcularSigmoide(X.dot(all_theta.T)), axis = 1)

    return p + 1

In [25]:
print(X.shape)
pred = predictOneVsAll(all_theta, X)
print('Precision del conjuto de entrenamiento: {:.2f}%'.format(np.mean(pred == y) * 100))
XPrueba = X[128:141, :].copy()
yPrueba = y[128:141].copy()
# XPrueba = [[11.44, 2.3, 2.41, 20, 96, 2.9, 2.79, 0.82, 1.83, 3.25, 0.8, 3.39, 625]]
# yPrueba = [2]
print(XPrueba.shape)
print(len(XPrueba))
# print(XPrueba)
# print(yPrueba.shape)
# print(yPrueba)

#print(np.ones((1)))
#p = np.zeros(1)
XPrueba = np.concatenate((np.ones((13, 1)), XPrueba), axis=1)
print(XPrueba)
# print(XPrueba.shape)
# print(XPrueba)
p = np.argmax(calcularSigmoide(XPrueba.dot(all_theta.T)), axis = 1)
print(p + 1)

(178, 13)
Precision del conjuto de entrenamiento: 99.44%
(13, 13)
13
[[1.000e+00 1.237e+01 1.630e+00 2.300e+00 2.450e+01 8.800e+01 2.220e+00
  2.450e+00 4.000e-01 1.900e+00 2.120e+00 8.900e-01 2.780e+00 3.420e+02]
 [1.000e+00 1.204e+01 4.300e+00 2.380e+00 2.200e+01 8.000e+01 2.100e+00
  1.750e+00 4.200e-01 1.350e+00 2.600e+00 7.900e-01 2.570e+00 5.800e+02]
 [1.000e+00 1.286e+01 1.350e+00 2.320e+00 1.800e+01 1.220e+02 1.510e+00
  1.250e+00 2.100e-01 9.400e-01 4.100e+00 7.600e-01 1.290e+00 6.300e+02]
 [1.000e+00 1.288e+01 2.990e+00 2.400e+00 2.000e+01 1.040e+02 1.300e+00
  1.220e+00 2.400e-01 8.300e-01 5.400e+00 7.400e-01 1.420e+00 5.300e+02]
 [1.000e+00 1.281e+01 2.310e+00 2.400e+00 2.400e+01 9.800e+01 1.150e+00
  1.090e+00 2.700e-01 8.300e-01 5.700e+00 6.600e-01 1.360e+00 5.600e+02]
 [1.000e+00 1.270e+01 3.550e+00 2.360e+00 2.150e+01 1.060e+02 1.700e+00
  1.200e+00 1.700e-01 8.400e-01 5.000e+00 7.800e-01 1.290e+00 6.000e+02]
 [1.000e+00 1.251e+01 1.240e+00 2.250e+00 1.750e+01 8.500e+01